### ISSUE TITLE
unexpected prefix: 969

### ISSUE THREAD

**Issue by andreortiz82** [wagn/wagn#476] opened 2015-08-07 17:10 UTC
This is my first time using **wagn** so maybe I'm missing something obvious. I'm opted to use `pg` and `thin` but aside from that, everything else is stock. There is a log in the `/log/production.log` that says: `Error rendering *head / raw: ArgumentError : unexpected prefix: 969`- Any ideas how to address this?

**Comment by ethn** [comment] 2015-08-07 17:17
Hi Andre, thanks for reaching out.

Can you paste a little more of that error message here?

Is this a new 1.16.1 installation?  And you successfully ran `wagn seed` without errors but then got this message when you started the server and loaded your first page?

**Comment by andreortiz82** [comment] 2015-08-07 19:35
Yes, I'm using gem version `1.16.1`. `wagn seed` runs fine and without errors. 
I run the project via `wagn server ` and this error is displayed on the page...

**Here is the full message**
```
Error message (visible to admin only)

unexpected prefix: 969

/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tmpdir.rb:110:in `make_tmpname'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tmpdir.rb:128:in `create'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tempfile.rb:133:in `initialize'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/mod/03_machines/lib/card/machine.rb:86:in `new'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/mod/03_machines/lib/card/machine.rb:86:in `block in included'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/mod/03_machines/lib/card/machine.rb:122:in `run_machine'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/mod/03_machines/lib/card/machine.rb:139:in `block in update_machine_output'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/auth.rb:100:in `as'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/auth.rb:109:in `as_bot'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/mod/03_machines/lib/card/machine.rb:136:in `update_machine_output'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/mod/03_machines/lib/card/machine.rb:182:in `ensure_machine_output'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/mod/03_machines/lib/card/machine.rb:171:in `machine_output_url'
/Users/andreortiz/Desktop/mysite/tmp/set/self/1042-head.rb:66:in `head_stylesheets'
/Users/andreortiz/Desktop/mysite/tmp/set/self/1042-head.rb:14:in `block (2 levels) in '
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:209:in `block (3 levels) in render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/view_cache.rb:45:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/view_cache.rb:45:in `fetch'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:208:in `block (2 levels) in render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/log.rb:541:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/log.rb:541:in `with_logging'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:207:in `block in render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:394:in `with_inclusion_mode'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:206:in `render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:185:in `method_missing'
/Users/andreortiz/Desktop/mysite/tmp/set/self/1042-head.rb:23:in `block (2 levels) in '
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:209:in `block (3 levels) in render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/view_cache.rb:45:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/view_cache.rb:45:in `fetch'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:208:in `block (2 levels) in render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/log.rb:541:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/log.rb:541:in `with_logging'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:207:in `block in render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:394:in `with_inclusion_mode'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:206:in `render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:185:in `method_missing'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:482:in `nest'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:414:in `prepare_nest'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:324:in `block in process_content_object'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/mod/01_core/chunk/include.rb:76:in `process_chunk'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/content.rb:61:in `block in process_content_object'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/content.rb:49:in `block in each_chunk'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/2.2.0/delegate.rb:87:in `each'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/2.2.0/delegate.rb:87:in `method_missing'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/content.rb:49:in `each_chunk'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/content.rb:61:in `process_content_object'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:323:in `process_content_object'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:314:in `process_content'
/Users/andreortiz/Desktop/mysite/tmp/set/all/1042-rich_html-content.rb:30:in `block (2 levels) in '
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:209:in `block (3 levels) in render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/view_cache.rb:45:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/view_cache.rb:45:in `fetch'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:208:in `block (2 levels) in render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/log.rb:541:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/log.rb:541:in `with_logging'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:207:in `block in render'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:394:in `with_inclusion_mode'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/card-1.16.1/lib/card/format.rb:206:in `render'
/Users/andreortiz/Desktop/mysite/tmp/set/all/1042-rich_html-content.rb:16:in `show'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wagn-1.16.1/rails/controllers/card_controller.rb:259:in `show'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wagn-1.16.1/rails/controllers/card_controller.rb:42:in `read'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:51:in `serve'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/server.rb:80:in `start'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:80:in `block in server'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wagn-1.16.1/lib/wagn/commands.rb:48:in `require'
/Users/andreortiz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/wagn-1.16.1/lib/wagn/commands.rb:48:in `'
script/wagn:6:in `require'
script/wagn:6:in `

```

**Comment by ethn** [comment] 2015-08-07 20:12
thanks for the log.

It's failing on just naming a tmp file (specifically CSS file autogenerated from cards). I'm struggling to see why that would happen to you (and not on our live, dev, or testing sites).

Will keep working.  In the meantime it might be worth trying `bundle update` to make sure you've got all the latest gems.  This appears to be a bug in a non-wagn gem, but I'd like to figure out which one!

**Comment by andreortiz82** [comment] 2015-08-10 15:17
I've had no luck with this - `bundle update` produces the same result. I tried manually changing permissions on the `tmp` directory but that didn't seem to have any effect. I'll keep poking around and see what I can find. Thanks again.

**Just incase it helps - here is the Gemfile.lock. Maybe you'll see something I'm missing.**

````
GEM
  remote: http://rubygems.org/
  specs:
    actionmailer (4.2.3)
      actionpack (= 4.2.3)
      actionview (= 4.2.3)
      activejob (= 4.2.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.3)
      actionview (= 4.2.3)
      activesupport (= 4.2.3)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.3)
      activesupport (= 4.2.3)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.3)
      activesupport (= 4.2.3)
      globalid (>= 0.3.0)
    activemodel (4.2.3)
      activesupport (= 4.2.3)
      builder (~> 3.1)
    activerecord (4.2.3)
      activemodel (= 4.2.3)
      activesupport (= 4.2.3)
      arel (~> 6.0)
    activerecord-session_store (0.1.1)
      actionpack (>= 4.0.0, < 5)
      activerecord (>= 4.0.0, < 5)
      railties (>= 4.0.0, < 5)
    activesupport (4.2.3)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    bootstrap-kaminari-views (0.0.5)
      kaminari (>= 0.13)
      rails (>= 3.1)
    builder (3.2.2)
    card (1.16.1)
      activerecord-session_store
      bootstrap-kaminari-views (~> 0.0.5)
      coderay (~> 1.0)
      coffee-script (~> 2.2)
      diff-lcs (~> 1.2)
      haml (~> 4.0)
      htmlentities (~> 4.3)
      kaminari (~> 0.16)
      paperclip (~> 4.2)
      recaptcha (~> 0.3)
      rmagick (~> 2.13)
      sass (~> 3.2)
      smartname (= 0.2.3)
      uglifier (~> 2.5)
      uuid (~> 2.3)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.7)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    daemons (1.2.3)
    diff-lcs (1.2.5)
    erubis (2.7.0)
    eventmachine (1.0.8)
    execjs (2.5.2)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    haml (4.0.6)
      tilt
    htmlentities (4.3.4)
    i18n (0.7.0)
    json (1.8.3)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    loofah (2.0.2)
      nokogiri (>= 1.5.9)
    macaddr (1.7.1)
      systemu (~> 2.6.2)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.6.1)
    mimemagic (0.3.0)
    mini_portile (0.6.2)
    minitest (5.8.0)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    paperclip (4.3.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)
    pg (0.18.2)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.3)
      actionmailer (= 4.2.3)
      actionpack (= 4.2.3)
      actionview (= 4.2.3)
      activejob (= 4.2.3)
      activemodel (= 4.2.3)
      activerecord (= 4.2.3)
      activesupport (= 4.2.3)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.3)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.6)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    railties (4.2.3)
      actionpack (= 4.2.3)
      activesupport (= 4.2.3)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    recaptcha (0.4.0)
    rmagick (2.15.3)
    sass (3.4.16)
    smartname (0.2.3)
      activesupport
      htmlentities (~> 4.3.0)
    sprockets (3.2.0)
      rack (~> 1.0)
    sprockets-rails (2.3.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    systemu (2.6.5)
    thin (1.6.3)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0)
      rack (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    uuid (2.3.8)
      macaddr (~> 1.0)
    wagn (1.16.1)
      card (= 1.16.1)
      rails (~> 4.2)

PLATFORMS
  ruby

DEPENDENCIES
  pg
  thin
  wagn

BUNDLED WITH
   1.10.5

````

**Comment by wrein** [comment] 2015-08-10 15:30
Same issue here...

**Comment by ethn** [comment] 2015-08-10 17:59
Thanks for the reports guys.

Andre, by those logs I'm guessing you're on a mac using ruby 2.2.2?   wrein, mind if I ask what you're using?

1.16.2 will be out very soon, and I'd really like to have a fix for this.  Wish I could figure out how to reproduce it...

**Comment by ethn** [comment] 2015-08-10 18:15
actually, sounds like the reason I'm struggling to reproduce that is that someone spotted and fixed this.  Hope to have the fix out today.

Sorry about that.

**Comment by andreortiz82** [comment] 2015-08-11 00:39
> Andre, by those logs I'm guessing you're on a mac using ruby 2.2.2?

That's correct.

**Comment by wrein** [comment] 2015-08-11 08:21
Maybe it's not important anymore, but that's my stack: gem 1.16.1 on osx 10.10.4, ruby 2.2.1p85, bundler 1.9.1, rubygems 2.4.5, rbenv 0.4.0

**Comment by ethn** [comment] 2015-08-15 20:44
Hey guys, wagn 1.16.2 is out.  Should fix this bug, but let me know if you have any more problems!

**Closed** 2015-08-15 20:44 UTC
